### ISSUE TITLE
CSVExternalSort drops rows when using CSVFormat with .format option

### ISSUE THREAD

**Issue by NTEREKAS** [lemire/externalsortinginjava#44] opened 2023-03-19 00:46 UTC
[ExternalSorting.zip](https://github.com/lemire/externalsortinginjava/files/11009947/ExternalSorting.zip)

Attached a project demonstrating issue ....

**Comment by NTEREKAS** [comment] 2023-03-19 00:50
Issue appears to be with lines containing escaped double-quotes

**Comment by lemire** [comment] 2023-03-19 18:31
That's not a valid CSV input...

```
"author","title"
"Dan Simmons","Hyperion"
"Dan Simmons","Hyperion"
"Dan Simmons","Hyperion"
"Dan Simmons","Hyperion"
"Dan Simmons","Hyperion"
"Dan Simmons","Hyperion"
"Douglas Adams","The Hitchhiker's Guide to the Galaxy"
"Douglas Adams","The Hitchhiker's Guide to the Galaxy"
"Douglas Adams","The Hitchhiker's Guide to the Galaxy
hello"
"Douglas Adams","The Hitchhiker's Guide to the Galaxy"
"Douglas Adams","The Hitchhiker's Guide to the Galaxy"
"Douglas Adams","The Hitchhiker's Guide to the Galaxy"
"Douglas Adams","The Hitchhiker's Guide to the Galaxy"
"Dan ""The Man"" Simmons","Hyperion"
```

**Comment by NTEREKAS** [comment] 2023-03-19 18:35
why? csv supports newlines

**Comment by lemire** [comment] 2023-03-19 18:58
I thought it was invalid because of all the quotes. You are correct, it is valid.

**Comment by lemire** [comment] 2023-03-19 18:59
I have added a test to the project corresponding to your use case. 
See
https://github.com/lemire/externalsortinginjava/pull/45


I am closing this issue, if you believe that there is a bug, please provide a reproducible test case. Ideally, you should provide a pull request.

**Closed by lemire** 2023-03-19 18:59 UTC
